{
	"version": 1645035048,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"c2webappstart.js",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/zemin-sheet0.png",
		"images/ilerispt-sheet0.png",
		"images/bilgispt-sheet0.png",
		"images/arkaplan-sheet0.png",
		"images/tiledbackground5.png",
		"images/cocuk1-sheet0.png",
		"images/anasayfa-sheet0.png",
		"images/sonucarkaplan.png",
		"images/sonucsprt-sheet0.png",
		"images/anasayfa1-sheet0.png",
		"media/dogruses (online-audio-converter.com).ogg",
		"media/yanlisses (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"sorular.txt.txt"
	]
}